fos_user: 
    db_driver: orm
    firewall_name: main
    #user_class: Sonata\UserBundle\Entity\BaseUser
    user_class:     App\Application\Sonata\UserBundle\Entity\User

    group:
        group_class:   App\Application\Sonata\UserBundle\Entity\Group    
        #group_class: Sonata\UserBundle\Entity\BaseGroup
        #group_manager: sonata.user.orm.user_manager

    service:
        user_manager: sonata.user.orm.user_manager

    from_email:
        address: robert.franczuk@gmail.com
        sender_name: robert.franczuk@gmail.com
