#sonata_user:
#        security_acl : true
#        manager_type: orm
sonata_user:
    class:
        user: App\Application\Sonata\UserBundle\Entity\User
        group: App\Application\Sonata\UserBundle\Entity\Group        
