#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#sonata_user_admin_security:
#    resource: '@SonataUserBundle/Resource/config/routing/admin_security.xml'
#    prefix: admin
#sonata_user_admin_resetting:
#    resource: '@SonataUserBundle/Resource/config/routing/admin_resetting.xml'
#    prefix: /admin/resetting
